/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chessgui;

import java.util.Timer;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class TimeMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public TimeMenu() {
        setTitle("Time Setting");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocation(700, 400);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        Five = new javax.swing.JButton();
        Fiveteen = new javax.swing.JButton();
        Thirty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        settings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settings.setText("  Time Setting");

        Five.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Five.setText("5 Minutes");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });

        Fiveteen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fiveteen.setText("15 Minutes");
        Fiveteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveteenActionPerformed(evt);
            }
        });

        Thirty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Thirty.setText("30 Minutes");
        Thirty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fiveteen, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Thirty, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(settings)))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settings)
                .addGap(18, 18, 18)
                .addComponent(Five, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fiveteen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Thirty, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        ChessDriver gui = new ChessDriver();
        gui.boardframe = new Window();
        gui.boardframe.setVisible(true);
        
        Timer timer = new Timer();
        ChessTimer task = new ChessTimer(60*5, (Board)gui.boardframe.component); //in seconds
        timer.schedule(task, 100, 1000);
        task.ShowTimer();
        
        this.setVisible(false);
    }//GEN-LAST:event_FiveActionPerformed

    private void FiveteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveteenActionPerformed
        ChessDriver gui = new ChessDriver();
        gui.boardframe = new Window();
        gui.boardframe.setVisible(true);
        
        Timer timer = new Timer();
        ChessTimer task = new ChessTimer(60*15, (Board)gui.boardframe.component); //in seconds
        timer.schedule(task, 100, 1000);
        task.ShowTimer();
        
        this.setVisible(false);
    }//GEN-LAST:event_FiveteenActionPerformed

    private void ThirtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirtyActionPerformed
        ChessDriver gui = new ChessDriver();
        gui.boardframe = new Window();
        gui.boardframe.setVisible(true);
        
        Timer timer = new Timer();
        ChessTimer task = new ChessTimer(60*30, (Board)gui.boardframe.component); //in seconds
        timer.schedule(task, 100, 1000);
        task.ShowTimer();
        
        this.setVisible(false);
    }//GEN-LAST:event_ThirtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Five;
    private javax.swing.JButton Fiveteen;
    private javax.swing.JButton Thirty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables
}
